version: "3"
services:
  video-streamer:
    image: orovium/video-streamer
    build:
      context: ./video-streamer
      dockerfile: Dockerfile
    container_name: video-streamer
    environment:
      - PORT=80
    env_file:
      - ./video-streamer/.env
    restart: "no"

  storage-service:
    image: orovium/storage-service
    build: 
      context: ./storage/azure
      dockerfile: Dockerfile
    container_name: storage-service
    environment:
      - PORT=80
    env_file:
      - ./storage/azure/.env

  caddy:
    image: orovium/caddy
    container_name: caddy
    build:
      context: ./caddy
      dockerfile: Dockerfile
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - ./caddy/.env

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-truman}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-capote}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    logging:
      driver: ${POSTGRES_LOG_DRIVER:-none}
  
volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  postgres:
    driver: local